version: '3.9'

services:
  frontend:
    image: tesla-portfolio-frontend
    container_name: portfolio-frontend
    build:
      context: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`localhost`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.middlewares=apikey@file"

    networks:
      - portfolio-net
      - traefik-net

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
      - portfolio-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth@file"

  database:
    image: tesla-portfolio-database
    container_name: portfolio-database
    build:
      context: ./database
    environment:
      POSTGRES_USER: tesla
      POSTGRES_PASSWORD: h4cktheplanet
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
  traefik-net:
    driver: bridge
